jobs:
  client-build:
    name: 'Frontend: Build'
    run_when:
      any branch is pushed: { type: branch, include_match: ^.*$ }
    task_defaults: &TASK_DEFAULTS
      environment_variables:
        CI: 'true'
      git_options:
        submodules:
          include_match: ^.*$
      traits:
        g2016: true
    task:
      scripts:
        build:
          timeout: 10 minutes
          body: 'cd client && { npm ci || npm i ;} && npm run build'

  client-specs:
    name: 'Frontend: Tests'
    run_when:
      any branch is pushed: { type: branch, include_match: ^.*$ }
    task_defaults: *TASK_DEFAULTS
    task:
      scripts:
        jest:
          timeout: 10 minutes
          body: 'cd client && { npm ci || npm i ;} && npm test -- -u && npm test'
