jobs:
  client-build:
    name: 'Frontend: Build'
    description:
      'Lints/checks the client app and builds a production/release version.'
    run_when:
      any branch is pushed: { type: branch, include_match: ^.*$ }
    task_defaults: &TASK_DEFAULTS
      environment_variables:
        CI: 'true'
      traits:
        g2016: true
    task:
      scripts:
        build:
          timeout: 10 minutes
          body: 'cd client && { npm ci || npm i ;} && npm run build'

  client-specs:
    name: 'Frontend: Tests'
    run_when:
      any branch is pushed: { type: branch, include_match: ^.*$ }
    task_defaults: *TASK_DEFAULTS
    task:
      scripts:
        jest:
          timeout: 10 minutes
          body: 'cd client && { npm ci || npm i ;} && npm test'
