jobs:
  backend-specs:
    name: 'Backend: Run specs'
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      generate_tasks:
        include_match: server/spec/.*_spec.rb
      task_defaults:
        include:
          - server/cider-ci/database_task-component.yml
          - server/cider-ci/ruby-bundle_task-component.yml
          - server/cider-ci/server_task-component.yml
          - server/cider-ci/uberjar_task-component.yml
        traits:
          JDK 8: true
          Leiningen 2: true
          g2016: true
        ports:
          LEIHS_PROCURE_HTTP_PORT:
            min: 3200
            max: 3299
        environment_variables:
          PROCUREMENT_DIR: '{{CIDER_CI_WORKING_DIR}}'
          DATABASE_NAME: leihs_procurement_{{CIDER_CI_TRIAL_ID}}
          LEIHS_DATABASE_URL: "jdbc:postgresql://localhost/{{DATABASE_NAME}}?max-pool-size=5"
          LEIHS_PROCURE_HTTP_BASE_URL: http://localhost:{{LEIHS_PROCURE_HTTP_PORT}}
          LEIHS_SECRET: '{{CIDER_CI_TRIAL_ID}}'
          RAILS_ENV: test
          RUBY: '{{RUBY_ENGINE}}-{{RUBY_VERSION}}'
          RUBY_ENGINE: ruby
          RUBY_VERSION: 2.6.0
        git_options:
          submodules:
            include_match: ^.*$
        scripts:
          test:
            body: |
              #!/usr/bin/env bash
              set -euxo
              env | sort
              export PATH=~/.rubies/$RUBY/bin:$PATH
              cd server
              mkdir -p log
              bundle exec rspec --backtrace ../$CIDER_CI_TASK_FILE
