#!/bin/sh -exu
source ./scripts/.helpers.sh

# for rails
export DATABASE_URL="${DATABASE_URL:-postgresql://localhost:5432/leihs_test_procure2?max-pool-size=5}"

# NOTE: profiles.cljs config broken for some reason, using ENV for now
export LEIHS_DATABASE_URL="jdbc:${DATABASE_URL}"
# auto find some open port
export LEIHS_HTTP_BASE_URL="${LEIHS_HTTP_BASE_URL:-http://localhost:$(get_open_port)}"
