#!/bin/sh -eu
source ./scripts/setup-test-env

cd database
RAILS_ENV=test bundle exec rake db:environment:set db:drop db:create || bundle exec rake  db:create
RAILS_ENV=test bundle exec rake db:environment:set db:migrate
cd ..

lein clean
lein with-profile test run "run"
